pre-commit:
  parallel: false
  commands:
    format:
      run: npm run format
      stage_fixed: true
    lint:
      run: npm run lint
      stage_fixed: true
    test:
      run: npm run test -- --run --reporter=verbose
