codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: 'diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - 'dist/**/*'
  - 'node_modules/**/*'
  - '__tests__/**/*'
  - '**/*.test.js'
  - 'coverage/**/*'
